### ISSUE TITLE
Unable to activate chef-10.12.0, because net-ssh-2.5.2 conflicts with net-ssh (~> 2.2.2)

### ISSUE THREAD

**Issue by rafaelmagu** [gofullstack/capistrano-chef#10]
Trying to enable capistrano-chef on a brand new install of OS X Mountain Lion, I get the following error whenever I add **require 'capistrano/chef'** to my Capfile.

```
/Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1637:in `raise_if_conflicts': Unable to activate chef-10.12.0, because net-ssh-2.5.2 conflicts with net-ssh (~> 2.2.2) (Gem::LoadError)
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:746:in `activate'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:780:in `block in activate_dependencies'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:766:in `each'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:766:in `activate_dependencies'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:750:in `activate'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:212:in `rescue in try_activate'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:209:in `try_activate'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:152:in `require'
    from Capfile:1:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:93:in `instance_eval'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:93:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:172:in `load_from_file'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:89:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:86:in `block in load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:86:in `each'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/configuration/loading.rb:86:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/cli/execute.rb:65:in `block in load_recipes'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/cli/execute.rb:65:in `each'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/cli/execute.rb:65:in `load_recipes'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/cli/execute.rb:31:in `execute!'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/gems/capistrano-2.12.0/bin/cap:4:in `<top (required)>'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/bin/cap:23:in `load'
    from /Users/rfonseca/.rbenv/versions/1.9.3-p194/gemsets/global/bin/cap:23:in `<main>'
```

**Comment by rafaelmagu** [comment]
After some brainstorming with much smarter Ruby folks than me, I resolved the above issue by uninstalling version 2.5.2 of net-ssh using gem uninstall.

**Comment by smith** [comment]
Cool, glad you got it figured out.
